name: Label New Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  label_issue:
    runs-on: ubuntu-latest
    
    steps:
      - name: Add "To Do" label
        uses: andymckay/labeler@1.0.1 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: To Do
